version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - redis

volumes:
  redis_data:
    driver: local
